apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-gitlab-postgresql.fullname" . }}
  labels:
    {{- include "simple-gitlab-postgresql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: postgresql
      protocol: TCP
      port: {{ include "simple-gitlab-postgresql.servicePort" . }}
      targetPort: postgresql
  selector:
    {{- include "simple-gitlab-postgresql.selectorLabels" . | nindent 4 }}
