apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "simple-gitlab-redis.fullname" . }}
  labels:
    {{- include "simple-gitlab-redis.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
