apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-gitlab-redis.fullname" . }}
  labels:
    {{- include "simple-gitlab-redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: redis
      protocol: TCP
      port: {{ template "simple-gitlab-redis.servicePort" . }}
      targetPort: redis
  selector:
    {{- include "simple-gitlab-redis.selectorLabels" . | nindent 4 }}
