apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-gitlab.fullname" . }}
  labels:
    {{- include "simple-gitlab.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: ssh
  selector:
    {{- include "simple-gitlab.selectorLabels" . | nindent 4 }}
